AWSTemplateFormatVersion: '2010-09-09'
Description: 'Amazon MSK Serverless Cluster with VPC Infrastructure - Pay per use, no idle costs'

Parameters:
  ClusterName:
    Type: String
    Default: taxi-kafka-msk
    Description: Name of the MSK cluster

  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]

  VpcCIDR:
    Type: String
    Default: '10.0.0.0/16'

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-vpc'
        - Key: Environment
          Value: !Ref Environment

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-igw'

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # Private Subnets (MSK Serverless requires private subnets)
  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Select [0, !Cidr [!Ref VpcCIDR, 6, 8]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-private-subnet-1'

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Select [1, !Cidr [!Ref VpcCIDR, 6, 8]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-private-subnet-2'

  PrivateSubnet3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [2, !GetAZs '']
      CidrBlock: !Select [2, !Cidr [!Ref VpcCIDR, 6, 8]]
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-private-subnet-3'

  # Route Table for private subnets (no NAT Gateway needed - Lambda runs outside VPC)
  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-private-rt'

  PrivateSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet1

  PrivateSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet2

  PrivateSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      SubnetId: !Ref PrivateSubnet3

  # Security Group for MSK Serverless
  MSKSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${ClusterName}-msk-sg'
      GroupDescription: Security group for MSK Serverless cluster
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 9098
          ToPort: 9098
          CidrIp: !Ref VpcCIDR
          Description: Kafka IAM auth
      SecurityGroupEgress:
        - IpProtocol: '-1'
          CidrIp: '0.0.0.0/0'
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-msk-sg'

  # MSK Serverless Cluster
  MSKServerlessCluster:
    Type: AWS::MSK::ServerlessCluster
    Properties:
      ClusterName: !Ref ClusterName
      ClientAuthentication:
        Sasl:
          Iam:
            Enabled: true
      VpcConfigs:
        - SubnetIds:
            - !Ref PrivateSubnet1
            - !Ref PrivateSubnet2
            - !Ref PrivateSubnet3
          SecurityGroups:
            - !Ref MSKSecurityGroup
      Tags:
        Name: !Ref ClusterName
        Environment: !Ref Environment
        Type: Serverless

  # Glue Schema Registry
  GlueSchemaRegistry:
    Type: AWS::Glue::Registry
    Properties:
      Name: !Sub '${ClusterName}-registry'
      Description: !Sub 'Schema Registry for ${ClusterName} MSK Serverless cluster'
      Tags:
        - Key: Name
          Value: !Sub '${ClusterName}-registry'
        - Key: Environment
          Value: !Ref Environment

Outputs:
  VPCId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub '${ClusterName}-VPCId'

  SubnetIds:
    Description: Private Subnet IDs
    Value: !Join [',', [!Ref PrivateSubnet1, !Ref PrivateSubnet2, !Ref PrivateSubnet3]]
    Export:
      Name: !Sub '${ClusterName}-SubnetIds'

  MSKSecurityGroupId:
    Description: MSK Security Group ID
    Value: !Ref MSKSecurityGroup
    Export:
      Name: !Sub '${ClusterName}-MSKSecurityGroupId'

  MSKClusterArn:
    Description: MSK Serverless Cluster ARN
    Value: !Ref MSKServerlessCluster
    Export:
      Name: !Sub '${ClusterName}-MSKClusterArn'

  GlueRegistryArn:
    Description: Glue Schema Registry ARN
    Value: !Ref GlueSchemaRegistry
    Export:
      Name: !Sub '${ClusterName}-GlueRegistryArn'

  ClusterType:
    Description: MSK Cluster Type
    Value: Serverless
